- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  tasks:
    - name: OneClick 
      command: defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking 1 #1本指でクリック
    - name: FinderFullPath
      command: defaults write com.apple.finder _FXShowPosixPathInTitle -bool true #Finderのタイトルバーにフルパスを表示
    - name: FinderAnimation
      command: defaults write com.apple.finder DisableAllAnimations -bool true #Finderアニメーション表示
    - name: HiddenFiles
      command: defaults write com.apple.finder AppleShowAllFiles -bool true #隠しファイル表示
    - name: ShowBatteryPercent
      command: defaults write com.apple.menuextra.battery ShowPercent YES
    - name: DateFormatting
      command: defaults write com.apple.menuextra.clock DateFormat -string "M\\U6708d\\U65e5(EEE)  H:mm:ss" #日付を表示
    - name: ScreenshotLocation
      command: defaults write com.apple.screencapture location ~/Downloads #スクリーンショットの保存先
    - name: ScreenshotShadow
      command: defaults write com.apple.screencapture disable-shadow -bool true #スクリーンショットの影消し
    - name: QuickLookAnimation
      command: defaults write -g QLPanelAnimationDuration -float 0 #QuickLookを開くアニメーションを切る
    - name: FunctionKey
      command: defaults write NSGlobalDomain com.apple.keyboard.fnState -bool true #Fuキーを標準のファンクションキーとして使用
    - name: Scrolldirection
      command: defaults write NSGlobalDomain com.apple.swipescrolldirection 0 #スクロール方向
    - name: FileExtension
      command: defaults write NSGlobalDomain AppleShowAllExtensions -bool true #拡張子を常に表示
    - name: Resize
      command: defaults write NSGlobalDomain NSWindowResizeTime -float 0.001 #リサイズ時間短縮

  roles:
    - homebrew
    - homebrew-cask
  vars:
    # Tap external Homebrew repositories.
    #
    # e.g.
    # - homebrew/binary
    homebrew_repositories:

    # Managed Homebrew packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state, install_options: [with-baz, enable-debug] }
    #
    # state choices: [head, latest, present, absent, linked, unlinked] (default: latest)
    # install_options: string or sequence (default: none)
    homebrew_packages:
      - ansible
      - git

    # Tap external Homebrew Cask repositories.
    homebrew_cask_repositories:
      - caskroom/versions

    # Managed Homebrew Cask packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state }
    #
    # state choices: [present, absent, installed, uninstalled] (default: present)
    homebrew_cask_packages:
      - adobe-reader
      - avast
      - appcleaner
      - caffeine
      - clipy
      - firefox-ja
      - flash
      - google-japanese-ime
      - iterm2
      - skype
      - sublime-text
      - the-unarchiver
      - vlc
